import { useState } from 'react';
import tubeschoolAPI from '../api/tubeschool.js';

export const useDownloadNotes = () => {
  const [downloading, setDownloading] = useState(false);

  // Helper to load external scripts dynamically
  const loadScript = (src) => {
    return new Promise((resolve, reject) => {
      if (document.querySelector(`script[src="${src}"]`)) {
        resolve();
        return;
      }
      const script = document.createElement('script');
      script.src = src;
      script.async = true;
      script.onload = resolve;
      script.onerror = reject;
      document.body.appendChild(script);
    });
  };

  const downloadNotes = async (sessionId) => {
    if (downloading) return;
    setDownloading(true);

    try {
      // 1. Load dependencies (html2pdf and marked for markdown parsing)
      await Promise.all([
        loadScript('https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.10.1/html2pdf.bundle.min.js'),
        loadScript('https://cdn.jsdelivr.net/npm/marked/marked.min.js')
      ]);

      // 2. Fetch Notes from API
      const data = await tubeschoolAPI.getNotes(sessionId);
      const markdownContent = data.note_content || "# No notes available";

      // 3. Convert Markdown to HTML using 'marked'
      const htmlContent = window.marked.parse(markdownContent);

      // 4. Create a temporary container for PDF generation
      const element = document.createElement('div');
      element.innerHTML = `
        <div style="font-family: 'Helvetica', 'Arial', sans-serif; padding: 40px; color: #000; background: #fff;">
          <h1 style="color: #ff7b3a; border-bottom: 2px solid #ff7b3a; padding-bottom: 10px; margin-bottom: 20px;">
            TubeSchool Notes
          </h1>
          <div style="font-size: 12px; color: #666; margin-bottom: 30px;">
            Session ID: ${sessionId}<br/>
            Generated on: ${new Date().toLocaleDateString()}
          </div>
          <div class="markdown-body" style="line-height: 1.6; font-size: 14px;">
            ${htmlContent}
          </div>
          <div style="margin-top: 50px; text-align: center; font-size: 10px; color: #999; border-top: 1px solid #eee; padding-top: 20px;">
            Generated by TubeSchool AI
          </div>
        </div>
      `;

      // 5. Generate PDF
      const opt = {
        margin:       0,
        filename:     `TubeSchool_Notes_${sessionId.slice(0,8)}.pdf`,
        image:        { type: 'jpeg', quality: 0.98 },
        html2canvas:  { scale: 2, useCORS: true },
        jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' }
      };

      await window.html2pdf().set(opt).from(element).save();

    } catch (err) {
      console.error('Failed to download notes:', err);
      alert('Failed to generate notes. Please try again.');
    } finally {
      setDownloading(false);
    }
  };

  return { downloadNotes, downloading };
};

export default useDownloadNotes;